version: '3.8'

services:
  # Base de datos MongoDB
  mongodb:
    image: mongo:6
    container_name: mongodb
    networks:
      - app_network
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  # Herramienta de gestión para MongoDB
  mongo-express:
    image: mongo-express:1
    container_name: mongo_express
    depends_on:
      - mongodb
    networks:
      - app_network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"

  # Backend (Node.js)
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/final-project-db
    ports:
      - "3000:3000"

  # Frontend (Angular)
  frontend:
    build:
      context: ./client/final-project
      dockerfile: Dockerfile
    container_name: frontend
    networks:
      - app_network
    ports:
      - "4200:4200"
    command: npm start

  # Backup Service
  mongo-backup:
    image: mongo:6
    container_name: mongo_backup
    depends_on:
      - mongodb
    networks:
      - app_network
    volumes:
      - ./backups:/backups
    environment:
      MONGO_INITDB_DATABASE: final-project-db
    entrypoint: |
      bash -c "
      while true; do
        mongodump --host=mongodb --out=/backups/backup-\$(date +%Y%m%d-%H%M%S) &&
        sleep 86400;  # Ejecutar cada 24 horas (86400 segundos)
      done
      "  

networks:
   app_network:
     driver: bridge

volumes:
  mongodb_data:
  backups:
