name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Clona el repositorio
    - name: Checkout source code
      uses: actions/checkout@v3

    # Configura Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Logueo en DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construcción de imágenes
    - name: Build and push backend image
      run: |
        docker build -t agustinmc/backend:latest ./server
        docker push agustinmc/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t agustinmc/frontend:latest ./client/final-project
        docker push agustinmc/frontend:latest

    # Ejecuta la aplicación localmente
    - name: Deploy locally
      run: |
        docker-compose down
        docker-compose pull
        docker-compose up -d --build
